### ISSUE TITLE
抽奖机貌似报错

### ISSUE THREAD

**Issue by dover** [MoPoQAQ/Script#2]
2020/12/08 09:01:42:695  <console>    [JS Console]: 
结束第1个【成就任务】：累计寻宝10次
2020/12/08 09:01:43:350  <console>    [JS Console]: {
   "SlotMachine" : {
      "conf" : [
         {
            "ddwPaperMoney" : 0,
            "dwPicNum" : 4,
            "dwPrizeType" : 2,
            "strPic" : "https://img10.360buyimg.com/promotepic/jfs/t1/145899/27/16946/10038/5fc9023eE48348a52/0581747b5885b0b5.png",
            "strPrizeName" : "满9-0.5元券"
         },
         {
            "ddwPaperMoney" : 100000,
            "dwPicNum" : 3,
            "dwPrizeType" : 0,
            "strPic" : "https://img10.360buyimg.com/promotepic/jfs/t1/140087/29/4155/13597/5f227683E75bb2651/a5516d7b379e5153.png",
            "strPrizeName" : ""
         },
         {
            "ddwPaperMoney" : 30000,
            "dwPicNum" : 2,
            "dwPrizeType" : 0,
            "strPic" : "https://img10.360buyimg.com/promotepic/jfs/t1/116076/14/13606/5677/5f22767fEec2993d4/3961aa817a80b0da.png",
            "strPrizeName" : ""
         },
         {
            "ddwPaperMoney" : 10000,
            "dwPicNum" : 1,
            "dwPrizeType" : 0,
            "strPic" : "https://img10.360buyimg.com/promotepic/jfs/t1/123245/8/8363/12685/5f22767aE4fdf6c55/3a065caf92bd1c98.png",
            "strPrizeName" : ""
         }
      ],
      "ddwConfVersion" : 61,
      "ddwOneceMoney" : 100,
      "dwDayPlayCount" : 20,
      "dwDayRemainCount" : 20,
      "dwFreeCount" : 1,
      "record" : [],
      "strCouponPool" : "jxcfd_slots_yhq_20200801",
      "strGoodsPool" : "jxcfd_slots_sw_20200801"
   },
   "iRet" : 0,
   "sErrMsg" : "",
   "strType" : "1"
}
2020/12/08 09:01:44:117  <console>    [JS Console]: 
【抽奖结果】

**Comment by MoPoQAQ** [comment]
已经修复了
