### ISSUE TITLE
通知那加个环境变量吧，默认不通知

### ISSUE THREAD

**Issue by allindusk** [MoPoQAQ/Script#3]
https://github.com/MoPoQAQ/Script/commit/d2290381c6f026efe7e91466b271888a0c1a6f2b

if ($.isNode())也太狠了

**Comment by MoPoQAQ** [comment]
@allindusk 通知啊，我都测试过了

**Comment by MoPoQAQ** [comment]
@MoPoQAQ 需要关闭通知？

**Comment by MoPoQAQ** [comment]
需要环境变量关闭通知？

**Comment by allindusk** [comment]
我知道通知，我的意思是改成用环境变量控制通不通知，现在默认通知顶不住

**Comment by MoPoQAQ** [comment]
@allindusk 嗯嗯，一会改

**Comment by allindusk** [comment]
好的谢谢，辛苦
